/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/components/pop_dog.glb -T --shadows 
Files: src/components/pop_dog.glb [6.33MB] > /Users/floydbenedikter/Desktop/REACT_REPO/react-course-v3/Three/pop_dog-transformed.glb [843.44KB] (87%)
Author: Dribliblu (https://sketchfab.com/Dribliblu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pop-dog-6a7b55d04987408ea24fc21d6884d17b
Title: Pop Dog
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF(
    'src/components/pop_dog-transformed.glb'
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.initialShadingGroup}
      />
    </group>
  );
}

useGLTF.preload('/pop_dog-transformed.glb');
